[profile.release]
debug = 1

[workspace]
members = [
    "crates/decorous-frontend",
    "crates/decorous-backend",
    "crates/core",
    "crates/superfmt",
    "crates/harpoon",
]

[workspace.dependencies]
rslint_parser = "0.3.1"
insta = { version = "1.30.0", features = ["yaml", "redactions"] }
