[workspace]
members = [
    "crates/decorous-frontend",
    "crates/decorous-backend",
    "crates/cli",
    "crates/superfmt",
]

[workspace.dependencies]
rslint_parser = "0.3.1"
insta = { version = "1.30.0", features = ["yaml", "redactions"] }
