[package]
name = "decorous-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.11.0"
rslint_parser = { workspace = true }
thiserror = "1.0.40"

[dev-dependencies]
insta = { workspace = true }
