[package]
name = "decorous-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
lightningcss = "1.0.0-alpha.44"
rslint_parser = "0.3.1"
thiserror = "1.0.40"

[dev-dependencies]
insta = "1.30.0"
