import requests

URL = "https://raw.githubusercontent.com/sveltejs/svelte/master/packages/svelte/src/compiler/utils/globals.js"
EXPORT_PATH = "../crates/decorous-frontend/src/component/globals.rs"


def main() -> None:
    text = requests.get(URL).text
    globals: list[str] = []
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith("'"):
            continue
        item = line[1:-2]
        globals.append(item)

    # Global defined by decorous
    globals.append("wasm")

    with open(EXPORT_PATH, "w") as f:
        f.write(
            f"""// This file was generated by scripts/gen_globals.py

pub const GLOBALS: [&str; {len(globals)}] = [\n"""
        )
        for g in globals:
            f.write(f'    "{g}",\n')
        f.write("];\n")


if __name__ == "__main__":
    main()
