name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install python3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install go
        uses: actions/setup-go@v4

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dart-sass
        run: npm install --global sass

      - name: Install emscripten
        uses: mymindstorm/setup-emsdk@v11

      - name: Install zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Rust wasm32-wasi
        run: rustup target add wasm32-wasi

      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build decorous
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --all --verbose
